// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow that suggests outfits based on user purchase history and style preferences.
 *
 * - suggestOutfits - A function that suggests outfits.
 * - SuggestOutfitsInput - The input type for the suggestOutfits function.
 * - SuggestOutfitsOutput - The return type for the suggestOutfits function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestOutfitsInputSchema = z.object({
  purchaseHistory: z
    .string()
    .describe('The user purchase history, as a JSON string.'),
  stylePreferences: z
    .string()
    .describe('The user style preferences, as a JSON string.'),
});
export type SuggestOutfitsInput = z.infer<typeof SuggestOutfitsInputSchema>;

const SuggestOutfitsOutputSchema = z.object({
  outfitSuggestions: z
    .string()
    .describe('Outfit suggestions based on the purchase history and style preferences.'),
});
export type SuggestOutfitsOutput = z.infer<typeof SuggestOutfitsOutputSchema>;

export async function suggestOutfits(input: SuggestOutfitsInput): Promise<SuggestOutfitsOutput> {
  return suggestOutfitsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestOutfitsPrompt',
  input: {schema: SuggestOutfitsInputSchema},
  output: {schema: SuggestOutfitsOutputSchema},
  prompt: `You are a personal stylist. Based on the user's purchase history and style preferences, you will suggest outfits.

Purchase History: {{{purchaseHistory}}}
Style Preferences: {{{stylePreferences}}}

Suggest outfits:`,
});

const suggestOutfitsFlow = ai.defineFlow(
  {
    name: 'suggestOutfitsFlow',
    inputSchema: SuggestOutfitsInputSchema,
    outputSchema: SuggestOutfitsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
